all:
	g++ calc_correlation.cpp ../DataAccessor/data_accessor.cpp ../baseline/baseline.cpp -o calc_correlation
	g++ read_correlation.cpp ../DataAccessor/data_accessor.cpp -o read_correlation
	g++ genre_predictions.cpp ../DataAccessor/data_accessor.cpp ../baseline/baseline.cpp -o genre_predictions
