mf:
	g++ run_matrix_factorization.cpp matrix_factorization.cpp sgd.cpp ../DataAccessor/data_accessor.cpp ../baseline/baseline.cpp -o run_matrix_factorization
opt-params:
	g++ optimize_mf_params.cpp matrix_factorization.cpp sgd.cpp ../DataAccessor/data_accessor.cpp ../baseline/baseline.cpp -o optimize_params